services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod --noauth

  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
  
  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    environment:
      REDIS_HOST: redis
    ports:
      - 6379:6379

  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin_container
    ports:
      - "8081:80" # Maps port 8080 on your machine to port 80 in the container
    restart: always