name: deploy-site

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  setup-build-deploy:
    name: Deploy Website
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Test
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies  
      run: npm install -g pnpm && pnpm install

    - name: Build Website
      run: pnpm build
    
    - name: Build Website
      run: pnpm website:build

    - name: Publish to Cloudflare Pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        command: pages deploy site/dist --project-name=airhorn --branch=main