name: release

on:
  workflow_dispatch:
  release:
    types: [released]

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  setup-build-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install -g pnpm && pnpm install

      - name: Build    
        run: pnpm build

      - name: Testing
        run: pnpm test:ci

      - name: create npmrc
        run: |
         echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
         echo "always-auth=true" >> ~/.npmrc

      - name: Publish Airhorn
        run: |
         pnpm publish:airhorn
      
      - name: Publish @airhornjs/aws
        run: |
         pnpm publish:aws

      - name: Publish @airhornjs/azure
        run: |
         pnpm publish:azure

      - name: Publish @airhornjs/twilio
        run: |
         pnpm publish:twilio 