name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WEBHOOK_MOCK_URL: http://localhost:80/post

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
           - 80:80

    strategy:
      matrix:
        node-version: ['16', '18', '20']

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Build    
      run: npm run build

    - name: Testing    
      run: npm run test
      
    - name: Code Coverage
      uses: codecov/codecov-action@v1.0.15
      with:
        token: ${{ secrets.CODECOV_KEY }}

