name: tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  WEBHOOK_MOCK_URL: http://localhost:80/post

jobs:
  setup-test:

    runs-on: ubuntu-latest
    services:
      httpbin:
        image: kennethreitz/httpbin
        ports:
           - 80:80

    strategy:
      matrix:
        node-version: ['20', '22']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Test Services    
      run: npm run test:services:start

    - name: Build    
      run: npm run build

    - name: Testing
      env:
        FIREBASE_CERT: ${{ secrets.FIREBASE_CERT }}
      run: npm run test

