name: tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Test Services    
      run: npm run test:services:start

    - name: Build    
      run: npm run build

    - name: Testing
      env:
        FIREBASE_CERT: ${{ secrets.FIREBASE_CERT }}
      run: npm run test

